apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    name: redis
spec:
  containers:
  - name: redis
    image: redis
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 6379

---
  
kind: Service
apiVersion: v1
metadata:
  name: my-redis-service
spec:
  selector:
    name: redis
  type:  ClusterIP 
  ports:
    - name: name-of-the-redis-port
      port: 6379
      targetPort:  6379
